- hosts: k8s-master
  tasks:
    - name: Copy Kubernetes manifest file to master node
      copy:
        src: ~/Ansible_2/Application/  # Path to the file on the Ansible machine
        dest: ~/Application/

    - name: Apply Kubernetes manifest using kubectl
      command: kubectl apply -f ~/Application/*