- hosts: k8s-master
  become: yes
  gather_facts: yes
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host={{ hostvars['k8s-master-1']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

    - name: join cluster
      shell: "{{ hostvars['k8s-master-1'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log





- hosts: k8s-master
  tasks:
    - name: install ingress
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/cloud/deploy.yaml

    - name: Enable kubectl completion and add aliases to .bashrc
      blockinfile:
        block: |
          alias k=kubectl
          export do='-o yaml --dry-run=client'
          source <(kubectl completion bash)
          complete -o default -F __start_kubectl k
        path: "/home/ubuntu/.bashrc"




    - name: Patch ingress service to be NodePort with default port 30000
      ansible.builtin.shell: |
            kubectl patch svc ingress-nginx-controller -n ingress-nginx --type=json -p "[{\"op\": \"replace\", \"path\": \"/spec/type\", \"value\": \"NodePort\"}, {\"op\": \"replace\", \"path\": \"/spec/ports/0/nodePort\", \"value\": 30000}]"
